#!/bin/zsh

### SETUP ###

function setup {
	# Check if Homebrew is installed
	brew update
	# Formulaes
	brew install openssl openvpn 
	#brew install autoconf binutils coreutils diffutils \
	#gnu-indent gnu-sed gnu-tar gnu-which gnupg \
	#gpatch grep gzip \
	#m4 ed flex gawk \
	#screen watch wdiff wget zip tree
	
	# Ask for level of setup to be done
	PS3='Which level of setup would you like to do? '
	select level in "Basic" "Intermediate" "Advanced" "None"; do
		case $level in
			Basic) basic_setup; break ;;
			Intermediate) intermediate_setup; break ;;
			Advanced) advanced_setup; break ;;
			None) echo "Installation stopped";break ;;
			*) echo "Invalid option $REPLY" ;;
		esac
	# Ask if Proton 
	echo "Do you want to install Proton suite ? [y/n] " 
	read yn
	case $yn in
		[Yy]* ) proton_setup; break;;
		[Nn]* ) break;;
	esac
	# Ask if Exegol 
	echo "Do you want to install Exegol ? [y/n] " 
	read yn
	case $yn in
		[Yy]* ) exegol_setup; break;;
		[Nn]* ) break;;
	esac
	# Ask if Copilot
	echo "Do you want to install Copilot ? [Y/n] "
	read yn
	case $yn in
		[Yy]* ) copilot_setup; break;;
		[Nn]* ) break;;
	esac
	echo "Setup complete."
	done
}

### SETUP FUNCTIONS ###

# Basic setup
function basic_setup {
	# Formulaes
  brew install --cask iterm2 brave-browser 
}
# Intermediate setup
function intermediate_setup {
	basic_setup
	brew install --cask notion notion-calendar slack discord
}
# Advanced setup
function advanced_setup {
	intermediate_setup
	brew install gdb nmap
	brew install --cask burp-suite postman wireshark metasploit
}

### SOFTWARE SETUP FUNCTIONS ###

# Proton setup function
function proton_setup {
	brew install --cask proton-mail proton-pass proton-drive proton-pass
	echo "Proton suite setup done."
}
# Docker setup function
function docker_setup {
	echo "Downloading Docker.dmg"
	curl -o https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_location=module ~/Downloads/Docker.dmg
	echo "Attaching Docker.dmg"
	sudo hdiutil attach ~/Downloads/Docker.dmg
	sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
	sudo hdiutil detach /Volumes/Docker
	echo "Docker install done."
}	
# Exegol setup function
function exegol_setup {
	# Downloads essential packages
	curl -o https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg ~/Downloads/Xquartz.pkg
	echo "Enable \"Allow connections from network clients\" in XQuartz preferences"
	docker_setup 
	echo "Enable File Sharing in Docker preferences to allow Exegol to access files"
	# Updating /opt
  echo "Making /opt writable..."
	sudo chown -R $USER /opt
	echo "/opt is now writable."
	git clone "https://github.com/ThePorgs/Exegol" /opt/Exegol
	brew install python-argcomplete
	python3 -m venv /opt/Exegol/Exegol-venv 
	source /opt/Exegol/Exegol-venv/bin/activate
	pip3 install --requirement /opt/Exegol/requirements.txt
	sudo ln -s /opt/Exegol/exegol.py /usr/local/bin/exegol
	echo "Exegol setup complete."
}	
# Copilot setup function
function copilot_setup {
	brew install gh npm 
	echo "Login to github"
	gh auth login
	gh extension install github/gh-copilot
	git clone https://github.com/github/copilot.vim.git \
  	~/.vim/pack/github/start/copilot.vim	
	echo "Input :Copilot Enable in Vim"
	vim
	echo "Copilot setup complete"
}

### FUNCTIONS ###

# Extract archives with extension provided
function extract {
  if [ -z "$1" ]; then
    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
  else
    if [ -f $1 ]; then
      case $1 in
        *.tar.bz2)   tar xvjf $1    ;;
        *.tar.gz)    tar xvzf $1    ;;
        *.tar.xz)    tar xvJf $1    ;;
        *.lzma)      unlzma $1      ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar x -ad $1 ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xvf $1     ;;
        *.tbz2)      tar xvjf $1    ;;
        *.tgz)       tar xvzf $1    ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *.xz)        unxz $1        ;;
        *.exe)       cabextract $1  ;;
        *)           echo "extract: '$1' - unknown archive method" ;;
      esac
    else
      echo "$1 - file does not exist"
    fi
  fi
}

# Vmware Fusion aliases for faster VM management
function vmw() {
  case $1 in
		vmx) find ~/Virtual\ Machines.localized/ -name "*.vmx" ;;
		list) vmrun list ;;
    start) vmrun start ~/Virtual\ Machines.localized/$2 nogui ;;
    stop) vmrun stop ~/Virtual\ Machines.localized/$2 hard ;;
    reset) vmrun reset ~/Virtual\ Machines.localized/$2 hard ;;
		check) vmrun checkToolsState ~/Virtual\ Machines.localized/$2 ;;
		tools) vmrun installTools ~/Virtual\ Machines.localized/$2 ;;
		ip) vmrun getGuestIPAddress ~/Virtual\ Machines.localized/$2 ;;
		ssh) ssh $(whoami)@$(vmrun getGuestIPAddress $2) ;;
		share) vmrun enableSharedFolders ~/Virtual\ Machines.localized/$2 ;;
    *) echo "Usage: vmware {vmx|list|start|stop|reset|check|tools|ip|ssh|share} <path_to_vm.vmx>" ;;
  esac
}

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# Show all the names (CNs and SANs) listed in the SSL certificate for a given domain
function getcertnames() {
	if [ -z "${1}" ]; then
		echo "ERROR: No domain specified.";
		return 1;
	fi;

	local domain="${1}";
	echo "Testing ${domain}…";
	echo ""; # newline

	local tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);

	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
		local certText=$(echo "${tmp}" \
			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
			no_serial, no_sigdump, no_signame, no_validity, no_version");
		echo "Common Name:";
		echo ""; # newline
		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
		echo ""; # newline
		echo "Subject Alternative Name(s):";
		echo ""; # newline
		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
		return 0;
	else
		echo "ERROR: Certificate not found.";
		return 1;
	fi;
}

function tre() {
	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
}

