### Environment Variables ###

## ZSH History setup ##
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=100
export SAVEHIST=100

## Colors ##
export CLICOLOR=1

## Terminal ##
#export TERM=xterm-256color

## Editor ##
export EDITOR=vim
export VISUAL=vim

## Path ##

# Add Homebrew's sbin to PATH
#export PATH="/usr/local/sbin:$PATH"
# Add Homebrew's bin to PATH
#export PATH="/usr/local/bin:$PATH"

## Language ##
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

## Python ##

## Node.js ##

## Ruby ##

## Java ##

## Android ##

## Go ##

## Rust ##

