### Environment Variables ###

## ZSH ##
export ZDOTDIR=$HOME/.zsh
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=100
export SAVEHIST=100

## Shell ##
export SHELL=/bin/zsh
export TERM=xterm-256color	
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

## Colors ##
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

## Editor ##
export EDITOR=vim
export VISUAL=vim

## Homebrew ##
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

## Python ##

## Node.js ##

## Ruby ##

## Java ##

## Android ##

## Go ##

## Rust ##

